# -------------------------------------------------
# --              FRAMEWORK global.R             --
# -------------------------------------------------
# NOTEs:                                         --
# Program code goes in "program" directory files --
# -------------------------------------------------
# *****        DO NOT EDIT THIS FILE       ***** --
# -------------------------------------------------

library(periscope)
library(shinyBS)


source(paste("program", "global.R", sep = .Platform$file.sep), local = TRUE)
