# -------------------------------------------------
# --               FRAMEWORK ui.R                --
# -------------------------------------------------
# NOTEs:                                         --
# Program code goes in "program" directory files --
# -------------------------------------------------
# *****       DO NOT EDIT THIS FILE        ***** --
# -------------------------------------------------

library(shinydashboardPlus)

periscope:::fw_reset_app_options()

source(paste("program", "ui_sidebar_right.R", sep = .Platform$file.sep),
       local = TRUE)
source(paste("program", "ui_body.R", sep = .Platform$file.sep),
       local = TRUE)


dashboardPagePlus(periscope:::fw_create_header_plus(),
                  periscope:::fw_create_sidebar(showsidebar = FALSE),
                  periscope:::fw_create_body(),
                  periscope:::fw_create_right_sidebar(),
                  sidebar_fullCollapse = TRUE)
